[teams]
names = [
    "Bayern München",
    "Bayer Leverkusen",
    "Eintracht Frankfurt",
    "Borussia Dortmund",
    "SC Freiburg",
    "Mainz 05",
    "RB Leipzig",
    "Werder Bremen",
    "VfB Stuttgart",
    "Borussia Mönchengladbach",
    "VfL Wolfsburg",
    "FC Augsburg",
    "Union Berlin",
    "FC St. Pauli",
    "TSG Hoffenheim",
    "1. FC Heidenheim",
    "1. FC Köln",
    "Hamburger SV",
]
